from __future__ import annotations

from typing import Protocol


class CodePlatform(Protocol):
    repo: str

    def create_pr(self, branch: str, title: str, body: str, base: str = "", labels: str = "") -> str: ...
    def pr_state(self, pr_number: int) -> str: ...
    def pr_is_merged(self, pr_number: int) -> bool: ...
    def find_pr_by_branch(self, branch: str) -> int | None: ...

    def get_review_threads(self, pr_number: int) -> dict: ...
    def get_pr_comments(self, pr_number: int) -> list[dict]: ...
    def reply_to_review_comment(self, pr_number: int, comment_id: int, body: str) -> bool: ...
    def comment_on_pr(self, pr_number: int, body: str) -> bool: ...
    def resolve_thread(self, thread_id: str) -> bool: ...
    def add_reaction(self, comment_id: int, reaction: str = "eyes") -> bool: ...
    def comment_has_reaction(self, comment_id: int, reaction: str = "eyes") -> bool: ...

    def get_pr_checks(self, pr_number: int) -> list[dict]: ...
    def get_failed_checks(self, pr_number: int) -> list[dict]: ...
    def checks_are_pending(self, pr_number: int) -> bool: ...
    def all_checks_pass(self, pr_number: int) -> bool: ...
    def format_failed_checks(self, failed_checks: list[dict]) -> str: ...
